create table if not exists public.feedback (id bigint generated by default as identity primary key,email text not null,type text not null default 'message',message text not null,created_at timestamptz not null default now());
alter table public.feedback enable row level security;
-- Do not create a public insert policy. The Vercel serverless function uses the service-role key.
